spring.application.name=foodshare
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:foodshare.db
spring.datasource.username=
spring.datasource.password=
spring.sql.init.mode=always

mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl


spring.data.redis.host=localhost
spring.data.redis.port=6379

redis.cache.enable=false